<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accepts Credit' => '',
    'Accepts Sfmnp' => '',
    'Accepts Snap' => '',
    'Accepts Wic' => '',
    'Accepts Wiccash' => '',
    'Are you sure you want to delete this item?' => '',
    'Cities' => '',
    'City ID' => '',
    'County' => '',
    'Create City' => '',
    'Create Market' => '',
    'Create Product' => '',
    'Create State' => '',
    'Delete' => '',
    'Facebook' => '',
    'ID' => '',
    'Location' => '',
    'Market ID' => '',
    'Market Name' => '',
    'Markets' => '',
    'Name' => '',
    'Othermedia' => '',
    'Product ID' => '',
    'Products' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Season1date' => '',
    'Season1time' => '',
    'Season2date' => '',
    'Season2time' => '',
    'Season3date' => '',
    'Season3time' => '',
    'Season4date' => '',
    'Season4time' => '',
    'State ID' => '',
    'States' => '',
    'Street' => '',
    'The requested page does not exist.' => '',
    'Twitter' => '',
    'Update' => '',
    'Update City: mode' => '',
    'Update Market: mode' => '',
    'Update Product: mode' => '',
    'Update State: mode' => '',
    'Updatetime' => '',
    'Updatetime Unparsed' => '',
    'Website' => '',
    'X' => '',
    'Y' => '',
    'Youtube' => '',
    'Zip' => '',
];
